import { Product } from './interface';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    code: 'f230fh0g3',
    title: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    stock: 24,
    author: 'James Clear',
    published: '2018-10-16',
  },
  {
    id: '2',
    code: 'f230fh0g4',
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Self-Help',
    price: 15.49,
    rating: 4.9,
    stock: 40,
    image: 'bamboo-watch.jpg',
    description: 'A guide on how small habits can lead to remarkable results.',
    published: '2018-10-16',
  },
  {
    id: '3',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    category: 'Programming',
    price: 28.99,
    rating: 4.7,
    stock: 12,
    image: 'clean-code.jpg',
    description: 'A handbook of agile software craftsmanship and coding best practices.',
    published: '2008-08-11',
  },
  {
    id: '4',
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    category: 'Finance',
    price: 10.99,
    rating: 4.6,
    stock: 35,
    image: 'bamboo-watch.jpg',
    description: 'An inspiring story about financial independence and mindset.',
    published: '1997-04-01',
  },
  {
    id: '5',
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    category: 'Programming',
    price: 26.5,
    rating: 4.8,
    stock: 14,
    image: 'bamboo-watch.jpg',
    description: 'Timeless lessons for software engineers to write maintainable code.',
    published: '1999-10-30',
  },
  {
    id: '6',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    category: 'Finance',
    price: 14.99,
    rating: 4.7,
    stock: 18,
    image: 'bamboo-watch.jpg',
    description: 'Stories exploring the hidden psychology behind financial decisions.',
    published: '2020-09-08',
  },
  {
    id: '7',
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'Productivity',
    price: 13.99,
    rating: 4.5,
    stock: 22,
    image: 'bamboo-watch.jpg',
    description: 'A guide to focused success in a distracted world.',
    published: '2016-01-05',
  },
  {
    id: '8',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    category: 'History',
    price: 19.99,
    rating: 4.8,
    stock: 28,
    image: 'bamboo-watch.jpg',
    description: 'Exploring how humans evolved from primitive tribes to global civilization.',
    published: '2011-06-04',
  },
];
